python train_v2.py \
    --database=nist \
    --detector=span \
    --block_type=vgg \
    --input_size=512 \
    --detector_weight= \
    --weight_save_path= \
    --check_save_path= \
    --log_file= \
    --epoch=200 \
    --batch=1 \
    --lr=0.0002 \
    --bce_weight=20 \
    --hinge_weight=1 \
    --seed=2021 \
    --gpu_id=6