python train_detector.py \
    --database=imd \
    --detector=refinednet \
    --input_size=512 \
    --weight_save_path= \
    --log_file= \
    --epoch=200 \
    --batch=4 \
    --lr=0.0002 \
    --seed=2023 \
    --gpu_id=0